# Generated by Django 2.0.1 on 2018-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordinvite',
            name='channel_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='discordinvite',
            name='guild_icon',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='discordinvite',
            name='guild_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='access_token',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
