# Generated by Django 2.0.1 on 2018-01-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bind', '0002_auto_20180113_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discorduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
